blank_issues_enabled: true
contact_links:
  - name: 💻 rescript-vscode
    url: https://github.com/rescript-lang/rescript-vscode/issues/new
    about: Reanalyze is being developed in the rescript-vscode repo. Please open your issue there.
