blank_issues_enabled: false
contact_links:
  - name: Using Reanalyze with ReScript?
    url: https://github.com/rescript-lang/rescript-vscode/issues/new
    about: Reanalyze is being developed in the rescript-vscode repo. Please open your issue there.
