open DeadCommon
open Common

type item = {exceptionPath : Path.t; locFrom : Location.t}

let delayedItems = ref []
let declarations = Hashtbl.create 1

(* The module name of a declaration comes from the source file name, e.g.
   "location" for location.ml, while paths in the typed tree use the OCaml
   module name "Location". Normalize so the two can be compared. *)
let normalizeModuleName name =
  let isInterface = name = Name.toInterface name in
  name |> Name.toInterface |> Name.toString |> String.capitalize_ascii
  |> Name.create ~isInterface

let add ~path ~loc ~(strLoc : Location.t) name =
  let exceptionPath =
    match List.rev (name :: path) with
    | moduleName :: rest -> List.rev (normalizeModuleName moduleName :: rest)
    | [] -> []
  in
  Hashtbl.add declarations exceptionPath loc;
  name
  |> addDeclaration_ ~posEnd:strLoc.loc_end ~posStart:strLoc.loc_start
       ~declKind:Exception ~moduleLoc:(ModulePath.getCurrent ()).loc ~path ~loc

(* Look up a declaration by path. Paths in the typed tree may be prefixed by
   a wrapper module that is not part of the declaration path (e.g. the
   [Dune__exe] or library alias module generated by dune), so on a miss retry
   with the outermost module dropped. *)
let rec findDeclaration exceptionPath =
  match
    Hashtbl.find_opt declarations
      (exceptionPath |> Path.moduleToImplementation)
  with
  | Some loc -> Some loc
  | None -> (
    match List.rev exceptionPath with
    | _ :: (_ :: _ :: _ as rest) -> findDeclaration (List.rev rest)
    | _ -> None)

let forceDelayedItems () =
  let items = !delayedItems |> List.rev in
  delayedItems := [];
  items
  |> List.iter (fun {exceptionPath; locFrom} ->
         match findDeclaration exceptionPath with
         | None -> ()
         | Some locTo ->
           addValueReference ~addFileReference:true ~locFrom ~locTo;
           (* Exception declarations are resolved through type references,
              like the non-delayed case in DeadValue. *)
           if !Config.analyzeTypes then
             TypeReferences.add locTo.loc_start locFrom.loc_start)

let markAsUsed ~(locFrom : Location.t) ~(locTo : Location.t) path_ =
  if locTo.loc_ghost then
    (* Probably defined in another file, delay processing and check at the end *)
    let exceptionPath = path_ |> Path.fromPathT in
    delayedItems := {exceptionPath; locFrom} :: !delayedItems
  else addValueReference ~addFileReference:true ~locFrom ~locTo
